server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://ep-long-wind-a8fxsjx3-pooler.eastus2.azure.neon.tech:5432/neondb
    username: neondb_owner
    password: npg_q1RzUawKj2AB
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: mySecretKey
  expiration: 86400000 # 1天

logging:
  level:
    root: INFO
    com.lifecheckin.backend: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

# MVC配置
spring.mvc:
  cors:
    allowed-origins: "http://localhost:3000"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600