server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://ep-long-wind-a8fxsjx3-pooler.eastus2.azure.neon.tech:5432/neondb
    username: neondb_owner
    password: npg_q1RzUawKj2AB
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: mySecretKey

  mvc:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

#logging:
#  level:
#    root: DEBUG

